"""Add customer fields to Booking

Revision ID: 0ab7c906b290
Revises: 
Create Date: 2025-10-11 18:32:28.711082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ab7c906b290'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('customer_email', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('customer_phone', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('customer_phone')
        batch_op.drop_column('customer_email')
        batch_op.drop_column('customer_name')

    # ### end Alembic commands ###
