"""intial tables

Revision ID: 280bfe93fba8
Revises: c5a4c05f62b2
Create Date: 2026-01-13 19:26:43.919274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '280bfe93fba8'
down_revision = 'c5a4c05f62b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('booking_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'bookings', ['booking_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('booking_id')

    # ### end Alembic commands ###
